version: '3.9'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456